<div id="log-popover-modal" class="modal fade">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">{ title }</h4>
            </div>
            <div class="modal-body">
                <h5><?php echo $this->translate('Recorded On')?>: { recordedOn }</h5>
                <raw content="{ text }"></raw>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary btn-save" data-dismiss="modal"><?php echo $this->translate('close') ?></button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script type="text/javascript">
    function (context) {
        var self = this;
        this.title = '<?php echo $this->translate('Log Information')  ?>';
        this.recordedOn = '-';
        this.text = '<?php echo $this->translate('No details available')  ?>';

        this.setLogInfo = function(title, recordedOn, text) {
            self.title = title;
            self.recordedOn = recordedOn;
            self.text = text;
            self.tags.raw.setContent(text);
            self.update();

            return self;
        }

        this.show = function () {
            console.log($(self.root).find("#log-popover-modal"));
            $(self.root).find("#log-popover-modal").modal("show");
        }
    }
</script>