<div id="log-popover-modal" class="modal fade">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">{ title }</h4>
            </div>
            <div class="modal-body">{ text }</div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary btn-save" data-dismiss="modal"><?php echo $this->translate('close') ?></button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script type="text/javascript">
    function (context) {
        var self = this;
        this.title = '<?php echo $this->translate('Log Information')  ?>';
        this.text = '<?php echo $this->translate('No details available')  ?>';

        this.setLogInfo = function(title, task) {

            self.title = title;

            self.update();

            context.app.renderInto(self, '.modal-body', 'task-monitor', {task : task});

            return self;
        }

        this.show = function () {
            $(self.root).find("#log-popover-modal").modal({backdrop : false}).modal("show");
        }
    }
</script>