<ul class="nav nav-pills nav-stacked">
    <li each="{ log in logs }"
        ><a href="#" onclick="{ parent.onProcessLogClick }" data-process-id="{ log.process_id }">{ parent.printDate(log.started_at) }&nbsp;<process-log-status log="{ log }"></process-log-status></a></li>
</ul>
<script type="text/javascript">
    function (context) {

        this.start_message = context.start_message;

        var self = this;

        this.logs = [];

        if (!_.isEmpty(this.start_message)) {
            $.getJSON('<?php echo $this->url('prooph.link/process_config/api/process_log') ?>?start_message=' + this.start_message)
            .then(
                function (data) {
                    self.logs = data.logs;
                    self.update();
                },
                $.failNotify
            );
        }

        this.printDate = function (iso8601Date) {

            var dateobj = new Date(iso8601Date);

            return dateobj.toLocaleString();
        }

        this.onProcessLogClick = function (e) {
            $.getJSON('<?php echo $this->url('prooph.link/process_config/api/process_log');  ?>/' + $(e.target).data("process-id"))
                .then(function (data) {
                    context.app.trigger("showProcessLog", data);
                }, $.failNotify);
        }
    }
</script>