<div class="row">
    <div id="app" class="col-md-12">
        <h1 class="text-center"><?php echo $this->translate('Process Manager') ?></h1>
        <process-manager></process-manager>
    </div>
</div>
<?php
$this->headLink()->appendStylesheet($this->basePath() . '/css/link_pm_flowchart.css');
$this->inlineScript()->appendFile($this->basePath() . '/js/jquery-ui.min.js');
$this->inlineScript()->appendFile($this->basePath() . '/js/jquery.jsPlumb.min.js');
$this->partial('prooph.link.process-manager/process-manager/partial/sidebar-left');

//Bootstrap ember app
$this->inlineScript()->captureStart();

$workflows    = json_encode($this->workflows);
$processes    = json_encode($this->processes);
$processTypes = json_encode($this->available_process_types);
$messages     = json_encode($this->available_messages);
$taskTypes    = json_encode($this->available_task_types);
$processingTypes  = json_encode($this->available_processing_types);
$connectors   = json_encode($this->connectors);
$locations    = json_encode($this->locations);
$manipulationScripts = json_encode($this->available_manipulation_scripts);

$lastLoggedProcess = $this->last_logged_process;


if (! empty($lastLoggedProcess['started_at'])) {
    $lastLoggedProcess['started_at'] = $this->dateFormat(
        \DateTime::createFromFormat(\DateTime::ISO8601, $lastLoggedProcess['started_at']),
        IntlDateFormatter::MEDIUM, // date
        IntlDateFormatter::MEDIUM, // time
        $this->plugin('translate')->getTranslator()->getLocale()
    );
}

if (! empty($lastLoggedProcess['finished_at'])) {
    $lastLoggedProcess['finished_at'] = $this->dateFormat(
        \DateTime::createFromFormat(\DateTime::ISO8601, $lastLoggedProcess['finished_at']),
        IntlDateFormatter::MEDIUM, // date
        IntlDateFormatter::MEDIUM, // time
        $this->plugin('translate')->getTranslator()->getLocale()
    );
}

foreach ($lastLoggedProcess['tasks'] as &$task) foreach ($task['events'] as &$event) {
    if (! empty($event['occurred_on'])) {
        $event['occurred_on'] = $this->dateFormat(
            \DateTime::createFromFormat(\DateTime::ISO8601, $event['occurred_on']),
            IntlDateFormatter::MEDIUM, // date
            IntlDateFormatter::MEDIUM, // time
            $this->plugin('translate')->getTranslator()->getLocale()
        );
    }
}

$lastLoggedProcess = json_encode($lastLoggedProcess);

echo <<<JS
window.PM = Prooph.Link.App.create(
    {
        workflows    : {$workflows},
        processes    : {$processes},
        processTypes : {$processTypes},
        messages     : {$messages},
        taskTypes    : {$taskTypes},
        processingTypes  : {$processingTypes},
        connectors   : {$connectors},
        locations    : {$locations},
        manipulationScripts : {$manipulationScripts},
        lastLoggedProcess : {$lastLoggedProcess},
        getConnector : function (id) {
            return _.findWhere(this.connectors, {id : id})
        },
        getProcessingType : function (typeClass) {
            return _.findWhere(this.processingTypes, { value : typeClass})
        }
    }
);

$(function () {
    PM.bootstrap("process-sidebar");
    PM.bootstrap("process-manager").ready();
});
JS;
$this->inlineScript()->captureEnd();
$this->inlineScript()->appendFile($this->basePath() . '/js/prooph/link/process-config/app.js');
?>