<div class="content"></div>
<script type="text/javascript">
    function (context) {
        var self = this;

        context.app.on("route", function (con) {

            var rm = con.routeMatch;

            if (rm.collection == "workflows" || ! rm.collection) {
                switch (true) {
                    case ! rm.index:
                        con.app.renderInto(con.app.tags["process-sidebar"], "#process-sidebar-container", "process-common-sidebar");
                        con.app.renderInto(self, ".content", "workflow-list");
                        return;
                    case rm.index == "create":
                        rm.action = rm.index;
                        rm.index = undefined;
                        con.app.renderInto(con.app.tags["process-sidebar"], "#process-sidebar-container", "process-flowchart-sidebar", {isNew : true});
                        con.app.renderInto(self, ".content", "process-flowchart", {isNew : true});
                        return;
                    case rm.action == "show":
                        con.app.renderInto(con.app.tags["process-sidebar"], "#process-sidebar-container", "process-flowchart-sidebar", {isNew : false, workflowId : rm.index});
                        con.app.renderInto(self, ".content", "process-flowchart", {isNew : false, workflowId : rm.index});
                        return;
                }
            }

            $(self.root).children(".content").html('<h2 class="text-danger text-center"><?php echo $this->translate('Page Not Found')  ?></h2>');
        });
    };
</script>